### ISSUE TITLE
Frends.RabbitMQ.Publish never closes any connections

### ISSUE THREAD

**Issue by skelendal** [FrendsPlatform/Frends.RabbitMQ#10]
Let's say you have a loop that sends 500 messages. The Publish task will create a connection/channel per message and never closes them. This leads to a situation where the Frends Process cannot be unloaded and a unhappy RabbitMQ server. Only way to close the connections is to terminate the Agent.

These should be some way to reuse the connection and/or force close the connection after use.

**Comment by RikuVirtanen** [comment]
I implemented IDisposable on the ConnectionHelper which had attributes for connections and models. This now forces the closing of the connections and channels.
