### ISSUE TITLE
Frends.RabbitMQ.Publish bug with simultaneous calls

### ISSUE THREAD

**Issue by RikuVirtanen** [FrendsPlatform/Frends.RabbitMQ#17]
Exceptions occur when making multiple simultaneous calls to the RabbitMQ server. 
The error seems to be from library and it might be able to minimize by using retries. 

`System.AggregateException: One or more errors occurred. (None of the specified endpoints were reachable) (None of the specified endpoints were reachable) (None of the specified endpoints were reachable) (None of the specified endpoints were reachable) ---> RabbitMQ.Client.Exceptions.BrokerUnreachableException: None of the specified endpoints were reachable ---> RabbitMQ.Client.Exceptions.PossibleAuthenticationFailureException: Possibly caused by authentication failure ---> RabbitMQ.Client.Exceptions.OperationInterruptedException: The AMQP operation was interrupted: AMQP close-reason, initiated by Library, code=0, text='End of stream', classId=0, methodId=0, cause=System.IO.EndOfStreamException: Reached the end of the stream. Possible authentication failure.`

**Comment by RikuVirtanen** [comment]
This was fixed but there is another bug with the new implementation. If the method GetCacheKeyFromMemoryCache() finds a cache key that has no underscore in it, the method will end up in exception: Index was outside the bounds of the array

**Comment by jefim** [comment]
Fix by #19
